
networks:
  dockervlan:
    external: true

services:
  pa-ammar:
    build: .
    container_name: PA-Ammar
    networks:
      dockervlan:
        ipv4_address: 172.23.5.99
    ports:
      - "2222:22"  # SSH-Port
      - "8000:8000"  # Django-Port
    stdin_open: true
    tty: true
    volumes:
      - ./workspace:/workspace
    depends_on:
      - pa-mysql-db

  pa-mysql-db:
    image: mysql:latest
    container_name: pa-mysql-db
    networks:
      dockervlan:
        ipv4_address: 172.23.5.98
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: example_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
