
services:
  pa-ammar:
    build: .
    container_name: PA-Ammar
    stdin_open: true
    tty: true
    volumes:
      - ./workspace:/workspace
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: pa-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: example_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
